apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "streamvisor.fullname" . }}"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    {{- include "streamvisor.standardLabels" . | nindent 4 }}
data:
{{ toYaml .Values.config | indent 2 }}
