apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ template "streamvisor.fullname" . }}-networkpolicy"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    {{- include "streamvisor.standardLabels" . | nindent 4 }}
  annotations:
{{- with .Values.networkPolicy.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "streamvisor.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{ toYaml .Values.networkPolicy.ingress | indent 4 }}
  egress:
{{ toYaml .Values.networkPolicy.egress | indent 4 }}
