{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "streamvisor.fullname" . }}-license-secret"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    app: {{ template "streamvisor.name" . }}
    chart: {{ template "streamvisor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: {{ template "streamvisor.fullname" . }}
type: Opaque
stringData:
  license.lic: {{- .Values.license | toYaml | indent 2 }}
{{- end }}