{{- if not .Values.secretCredentials.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "streamvisor.fullname" . }}-secret"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    app: {{ template "streamvisor.name" . }}
    chart: {{ template "streamvisor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: {{ template "streamvisor.fullname" . }}
type: Opaque
data:
  {{- if .Values.secretCredentials.admin}}
  STREAMVISOR_BOOTSTRAPADMIN_ENABLE: "true"
  STREAMVISOR_BOOTSTRAPADMIN_NAME: {{ .Values.secretCredentials.admin.username | b64enc }}
  STREAMVISOR_BOOTSTRAPADMIN_PASSWORD: {{ .Values.secretCredentials.admin.password | b64enc }}
  STREAMVISOR_BOOTSTRAPADMIN_EMAIL: {{ .Values.secretCredentials.admin.email | b64enc }}
  {{- end }}
{{- end }}
