apiVersion: v1
kind: Service
metadata:
  name: "{{ template "streamvisor.fullname" . }}"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    {{- include "streamvisor.standardLabels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "streamvisor.matchLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
