{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "streamvisor.fullname" . }}-claim"
  namespace: {{ template "streamvisor.namespace" . }}
  labels:
    {{- include "streamvisor.standardLabels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
spec:
  accessModes:
{{toYaml .Values.persistence.accessModes | indent 4}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{.Values.persistence.storageClass}}
{{- end }}
{{- end }}
  resources:
    requests:
      storage: {{.Values.persistence.size | quote}}
{{- end -}}
